version: '3.7'
services:
  postgres:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 54329:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: